[workspace]
resolver = "3"
members = ["oj-evaluator", "oj-generator", "editor", "shared"]

[workspace.package]
version = "0.2.5"
edition = "2024"

[profile.release]
opt-level = 3
# opt-level = "z"
codegen-units = 1
strip = true
lto = true
panic = "abort"

[workspace.dependencies]
anyhow = "1.0.102"
serde = { version = "1.0.228", features = ["derive"] }
serde_yaml_ng = "0.10.0"
owo-colors = "4.3.0"
