[workspace]
resolver = "3"
members = ["oj-evaluator", "oj-generator", "editor", "shared", "i18n-macro"]

[workspace.package]
version = "0.2.6"
edition = "2024"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
unwrap_used = "warn"
expect_used = "warn"
if_then_some_else_none = "deny"
empty_enum_variants_with_brackets = "deny"
empty_structs_with_brackets = "deny"
separated_literal_suffix = "deny"
semicolon_outside_block = "deny"
non_zero_suggestions = "deny"
string_lit_chars_any = "deny"
use_self = "deny"
useless_let_if_seq = "deny"
branches_sharing_code = "deny"
equatable_if_let = "deny"
option_if_let_else = "allow"
items_after_statements = "allow"

[profile.release]
opt-level = 3
# opt-level = "z"
codegen-units = 1
strip = true
lto = true
panic = "abort"

[workspace.dependencies]
anyhow = "1.0.102"
serde = { version = "1.0.228", features = ["derive"] }
serde_yaml_ng = "0.10.0"
owo-colors = "4.3.0"
