[package]
name = "editor"
version = "0.2.3"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bit-set = "0.8.0"
crossterm = "0.29.0"
either = "1.15.0"
ropey = "1.6.1"
unicode-segmentation = "1.12.0"
unicode-width = "0.2.1"

