[package]
name = "oj-evaluator"
version = "0.2.4"
edition = "2024"

[dependencies]
shared = { path = "../shared" }
tokio = { version = "1.47.1", features = ["io-util", "macros", "process", "rt-multi-thread", "time"] }
clap = { version = "4.5.32", features = ["derive"] }
log = "0.4.27"
simplelog = "0.12.2"
owo-colors = "4.2.2"
num-format = "0.4.4"
prettytable-rs = "0.10.0"
similar = { version = "2.7.0", features = ["inline", "unicode"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_yml = "0.0.12"
anyhow = "1.0.100"
either = "1.15.0"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.59.0", features = ["Win32_Foundation", "Win32_Security", "Win32_System_Threading", "Win32_System_Diagnostics_ToolHelp", "Win32_System_JobObjects"] }

[target.'cfg(target_os = "linux")'.dependencies]
cgroups-rs = "0.3.4"
rand = "0.9.1"
libc = "0.2.177"
itoa = "1.0.15"